name: module_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  get: ^4.6.6
  flutter_native_splash: ^2.3.6
  iconsax: ^0.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  fl_chart: ^0.65.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  flutter_any_logo: ^1.1.1
  provider: ^6.1.1
  google_fonts: ^4.0.1
  animated_toggle_switch: ^0.6.2
  awesome_dialog: ^3.2.0
  flutter_spinkit: ^5.2.0
  easy_splash_screen: ^1.0.4
  shared_preferences: ^2.2.2
  google_mobile_ads: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - images/
    - assets/img/

  #--------------- LOCAL FONTS ------------------#
